name: Tflint

on:
  workflow_call:
    inputs:
      tflint-version:
        description: tflint version to use.
        type: string
        default: 0.33.0
      project-folder:
        description: The folder containing the terraform project.
        type: string
        default: .

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}

     # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: v${{ inputs.tflint-version }}

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact